#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t aspectnotebook \
                         -e Aspect_DIR=/apps/share64/debian10/aspect/aspect-2.5.0pre \
                         -C "start_jupyterlab -T @tool" \
                         -u anaconda-7 \
                         -u aspect-2.5.0-pre \
                         -r none \
                         -w headless
